services:
  - type: web
    name: learning-recommender-backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt && python download_models.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300
    envVars:
      - key: HF_DISTILBERT_REPO
        value: "Bhanu6301/distilbert-finetuned"
      - key: HF_RECOMMENDER_REPO
        value: "Bhanu6301/finetuned-recommender-v2"
      - key: HF_TOKEN
        value: ""   # Add your HuggingFace token in Render dashboard
