services:
  - type: web
    name: learning-recommender-backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: HF_DISTILBERT_REPO
        value: "Bhanu6301/distilbert-finetuned"
      - key: HF_RECOMMENDER_REPO
        value: "Bhanu6301/finetuned-recommender-v2"
      - key: HF_TOKEN
        value: ""   # Add your HuggingFace token in Render dashboard
